name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour SonarCloud

      # Installer Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Tester Snyk dans la PR
      - name: Test Snyk in Pull Request
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Installer jq pour analyser les résultats Snyk
      - name: Install jq
        run: sudo apt-get install jq

      # Commenter sur PR avec les résultats Snyk
      - name: Comment on PR with Snyk issues
        run: |
          PR_COMMENT="Snyk Security Scan Report: \n\n"
          
          # Test Snyk et récupération des résultats
          snyk test --all-projects --json | jq -r '.issues[]? | "- \(.title) (\(.severity))\n  - \(.url)"' | while read -r issue; do
            PR_COMMENT+="$issue\n"
          done

          # Affichage du contenu du commentaire pour debug
          echo "Comment content: $PR_COMMENT"  # Debug print to check the comment content

          # Commentaire sur la PR via l'API GitHub
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -d "{\"body\": \"$PR_COMMENT\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Exécution de l'analyse de sécurité avec Snyk (Backend)
      - name: Run Snyk Security Scan (Backend)
        run: |
          cd mern/backend
          snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Exécution de l'analyse de sécurité avec Snyk (Frontend)
      - name: Run Snyk Security Scan (Frontend)
        run: |
          cd mern/frontend
          snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Correction des vulnérabilités avec Snyk (Backend)
      - name: Fix vulnerabilities with Snyk (Backend)
        run: |
          cd mern/backend
          snyk protect
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Correction des vulnérabilités avec Snyk (Frontend)
      - name: Fix vulnerabilities with Snyk (Frontend)
        run: |
          cd mern/frontend
          snyk protect
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Surveillance avec Snyk (Backend)
      - name: Monitor with Snyk (Backend)
        run: |
          cd mern/backend
          snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Surveillance avec Snyk (Frontend)
      - name: Monitor with Snyk (Frontend)
        run: |
          cd mern/frontend
          snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Backend Build & Scan
      - name: Build and Load Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }} ./mern/backend
          docker images

      # Installation de Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.50.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      # Scan de l'image Docker Backend pour les vulnérabilités
      - name: Scan Backend Docker Image for Vulnerabilities
        run: |
          trivy image --scanners vuln --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

      # Installation de SonarScanner
      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner

      # Exécution de l'analyse SonarCloud pour le Backend
      - name: Run SonarCloud Analysis for Backend
        run: |
          ./sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=Saif-hadd_Mern-Docker-Compose -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.sources=./mern/backend -Dsonar.sourceEncoding=UTF-8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Push de l'image Backend
      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

      # Frontend Build & Scan
      - name: Build and Load Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} ./mern/frontend
          docker images

      # Scan de l'image Docker Frontend pour les vulnérabilités
      - name: Scan Frontend Docker Image for Vulnerabilities
        run: |
          trivy image --scanners vuln --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

      # Exécution de l'analyse SonarCloud pour le Frontend
      - name: Run SonarCloud Analysis for Frontend
        run: |
          ./sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=Saif-hadd_Mern-Docker-Compose -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.sources=./mern/frontend -Dsonar.sourceEncoding=UTF-8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Push de l'image Frontend
      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

      # Reporting and Notifications
      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Build succeeded for commit ${{ github.sha }}! Backend & Frontend images pushed to Docker Hub."}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Build failed for commit ${{ github.sha }}! Check the logs for details."}' ${{ secrets.SLACK_WEBHOOK_URL }}
