name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - main  # Trigger only on the main branch

jobs:
  docker:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Step 1: Checkout the source code
      - name: Checkout
        uses: actions/checkout@v4  # Ensure the code is cloned from the repo

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3  # Login to Docker Hub using GitHub secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password

      # Step 3: Set up QEMU for multi-platform compatibility
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 5: Build and Load Backend Image into Docker Daemon
      - name: Build and Load Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }} ./mern/backend
          docker images  # Verify the image is available locally

      # Step 6: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.50.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version  # Verify installation

      # Step 7: Scan Backend Image
      - name: Scan Docker Image for Vulnerabilities
        run: |
          trivy image --scanners vuln  --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}    

      # Step 8: Push Backend Image
      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

      # Step 9: Build and Push Frontend Image
      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./mern/frontend  # Frontend directory
          push: true  # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}  # Dynamic username tagging