name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - main  # Déclencher uniquement sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser un runner Ubuntu

    steps:
      # Étape 1: Récupérer le code source
      - name: Checkout du code
        uses: actions/checkout@v4  # Vérifie que le code est cloné depuis le repo

      # Étape 2: Connexion à Docker Hub
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3  # Connexion à Docker Hub via les secrets GitHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Nom d'utilisateur Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Mot de passe Docker Hub

      # Étape 3: Activer Docker Buildx
      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      # Étape 4: Build et Push Backend avec buildx
      - name: Build et push Backend
        run: |
          docker buildx build --tag ${{ secrets.DOCKER_USERNAME }}/backend:latest -f ./mern/backend/Dockerfile ./mern/backend --push

      # Étape 5: Build et Push Frontend avec buildx
      - name: Build et push Frontend
        run: |
          docker buildx build --tag ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f ./mern/frontend/Dockerfile ./mern/frontend --push
